#!/usr/bin/env bash
set -Eeuo pipefail

SOURCE_WS="${PANJIAN_WS:-/home/lxr20/lxr/panjian_ws}"
TARGET_WS="${IGIBSON_MPC_WS:-/home/lxr20/lxr/igibson_mpc_ws}"
CASADI_PREFIX="${CASADI_PREFIX:-/home/lxr20/lxr/local/casadi-3.7.0}"

if [[ ! -d "$SOURCE_WS" ]]; then
  echo "Source workspace not found: $SOURCE_WS" >&2
  exit 1
fi

mkdir -p "$TARGET_WS/src"

link_package() {
  local source_rel="$1"
  local link_name="$2"
  local source_path="${SOURCE_WS}/${source_rel}"
  local link_path="${TARGET_WS}/src/${link_name}"

  if [[ ! -e "$source_path" ]]; then
    echo "Required package path missing: $source_path" >&2
    exit 1
  fi

  if [[ -L "$link_path" ]]; then
    local current_target
    current_target="$(readlink -f "$link_path")"
    if [[ "$current_target" == "$(readlink -f "$source_path")" ]]; then
      echo "Reusing symlink: $link_path -> $source_path"
      return 0
    fi
    echo "Symlink exists but points elsewhere: $link_path -> $current_target" >&2
    exit 1
  elif [[ -e "$link_path" ]]; then
    echo "Path exists and is not a symlink: $link_path" >&2
    exit 1
  fi

  ln -s "$source_path" "$link_path"
  echo "Linked $link_path -> $source_path"
}

link_package "planner/mpc_secbf" "mpc_secbf"
link_package "planner/semantic_guard" "semantic_guard"
link_package "perception/semantic_fusion" "semantic_fusion"
link_package "planner/vomp_planner/traj_planner" "traj_planner"
link_package "perception/plan_env" "plan_env"
link_package "simulation_tools/dynamic_simulator" "dynamic_simulator"
link_package "simulation_tools/map_generator" "map_generator"
link_package "simulation_tools/robot_simulator" "robot_simulator"
link_package "swarm_test" "swarm_test"
link_package "integrations/igibson/igibson_mpc_bridge" "igibson_mpc_bridge"

WHITELIST="semantic_fusion;mpc_secbf;semantic_guard;plan_env;dynamic_simulator;traj_planner;map_generator;robot_simulator;swarm_test;igibson_mpc_bridge"

cat > "$TARGET_WS/README_igibson_mpc_ws.txt" <<EOF
This workspace is generated by:
  $SOURCE_WS/integrations/igibson/scripts/05_prepare_isolated_mpc_ws.sh

Build:
  cd $TARGET_WS
  source /opt/ros/noetic/setup.bash
  catkin_make \\
    -DCATKIN_WHITELIST_PACKAGES="$WHITELIST" \\
    -DCMAKE_CXX_STANDARD=14 \\
    -DCMAKE_PREFIX_PATH="$CASADI_PREFIX;/opt/ros/noetic"

Run bridge:
  source /opt/ros/noetic/setup.bash
  source $TARGET_WS/devel/setup.bash
  roslaunch igibson_mpc_bridge igibson_minimal_bridge.launch
EOF

echo "Isolated iGibson MPC workspace prepared at $TARGET_WS"
echo "Next build command:"
echo "  cd $TARGET_WS && source /opt/ros/noetic/setup.bash && catkin_make -DCATKIN_WHITELIST_PACKAGES=\"$WHITELIST\" -DCMAKE_CXX_STANDARD=14 -DCMAKE_PREFIX_PATH=\"$CASADI_PREFIX;/opt/ros/noetic\""
