<?xml version="1.0"?>
<package format="2">
  <name>mpc_secbf</name>
  <version>0.1.0</version>
  <description>MPC-SECBF: Model Predictive Control with Semantic Enhanced Control Barrier Function</description>
  <maintainer email="1147975692@qq.com">Rechardluxry</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>roscpp</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>visualization_msgs</build_depend>
  <build_depend>semantic_guard</build_depend>
  <build_depend>semantic_fusion</build_depend>

  <build_export_depend>roscpp</build_export_depend>
  <build_export_depend>semantic_guard</build_export_depend>

  <exec_depend>roscpp</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>semantic_guard</exec_depend>
  <exec_depend>semantic_fusion</exec_depend>
</package>
